### ISSUE TITLE
add shebang

### ISSUE THREAD

**Issue by umlaeute** [rbdannenberg/vc#1]
rather than using a `vc.sh` wrapper that just calls python with the py-file at some hardcoded location, how about turning the .py-file itself exectuable?

like so:

~~~sh
$ chmod +x vc.py
$ head -5 vc.py
#!/usr/bin/env python3
# vc.py -- wrapper for git. I never want to use git again.
#
# Roger B. Dannenberg
# June 2021
$  ./vc.py -h
vc - version control. A wrapper to avoid git exposure and damage.
[...]
~~~

you could also remove the `.py` extension, at least on Un*xes, but i'm not sure whether Windows will then complain :-)

**Comment by rbdannenberg** [comment]
Thanks, I added the "#!/usr/bin/env python3" line. I invoke vc by adding 
this to my .alias file: "alias vc="python3 ~/vc/vc.py". Alternatively, I 
would recommend "cp vc.py ~/bin/vc" and "chmod +x ~/bin/vc" (assuming 
~/bin/ is on PATH). Either way lets you run "vc" instead of "./vc.py".

As an aside, renaming to vc would work on Windows too, e.g. "python3 vc" 
works after renaming vc.py to vc, but I think you still need a vc.bat to 
be able to simply type "vc ..." and run the program, so there's not much 
point to renaming.

**Comment by umlaeute** [comment]
cool.
i see you also changed `vc.py` to be executable :rocket:
